### ISSUE TITLE
Request to transfer ownership of this package on NPM

### ISSUE THREAD

**Issue by BTOdell** [VoiceNGO/path-resolve#1]
This package is currently published on NPM here: https://www.npmjs.com/package/path-resolve
The package is published by Mark Kahn (zyklus).

I am reaching out to the current owner of this NPM package (zyklus) with the hope that I can take ownership of this package with its name "path-resolve" and turn it into a polyfill for the Node.js path.resolve() function. I have searched the NPM repository for a browser-compatible polyfill with this functionality and have not been able to find one.

Given the fact that this NPM package has a relatively small number of downloads and dependencies, I think it would be reasonable to allow me to re-purpose this NPM package as something else. The current version of the package is 0.0.1. I would re-release the package at version 1.0.0 and so semantic versioning would prevent existing users of the package from auto-updating to the new package and having their code break.

Please consider releasing the package ownership to me (btodell) so I may re-purpose this package.
Thank you,
Bradley Odell

**Comment by zyklus** [comment]
Hi,

Can you expand on why you feel path.resolve needs a polyfill?  If this is
intended for browsers I don't personally see the need to mimic node's
APIs.  If it's for node, path.resolve has been around forever and doesn't
need a polyfill.

Thanks!
-Mark

**Comment by BTOdell** [comment]
The [/path] portion of a URI is nearly identical to a Unix path.

`scheme:[//[user[:password]@]host[:port]][/path][?query][#fragment]`

Paths are a generic concept. Browsers can handle both absolute and relative paths (relative to the window.location). I feel the path.resolve functionality should be available in the browser too and I feel the best way to make this functionality available would be through a polyfill for Node.js path.resolve.

I have found packages similar to Node.js path.resolve:
- [resolve-url](https://www.npmjs.com/package/resolve-url)
- [resolve-path](https://www.npmjs.com/package/resolve-path)

But if you read the documentation for each of these packages, they don't perform the same operation as Node.js path.resolve.

"path-resolve" would be an intuitive name for a Node.js polyfill for path.resolve. I can always release it under another name but I feel that using "path-resolve" would be best so I'm asking you.

**Comment by MarkKahn** [comment]
I agree that your tool has use, but strongly disagree with calling it `path.resolve`.  The concept of a URL is similar to, but not identical to, a path.  This is just a confusing name for a URL parsing tool
